spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}

esi:
  baseUrl: https://esi.evetech.net/latest/

mailer:
  discord:
    token: ${DISCORD_TOKEN}
  ceoName: Skriwel
  ceoId: 2116434445

server:
  port: ${SERVER_PORT:8080}
