spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}

esi:
  baseUrl: https://esi.evetech.net/latest/

eve:
  baseUrl: https://esi.evetech.net/latest/
  loginUrl: https://login.eveonline.com/
  clientId: ${EVE_CLIENT_ID}
  secretKey: ${EVE_SECRET_KEY}
  issuer: login.eveonline.com
  audience: EVE Online

discord:
  token: ${DISCORD_TOKEN}
  applicationId: ${DISCORD_APPLICATION_ID}

mailer:
  ceoName: ${CEO_NAME:Skriwel}
  ceoId: ${CEO_ID:2116434445}

server:
  port: ${SERVER_PORT:8080}
